// THIS IS AN INTERPRETED, HIGH-LEVEL PROGRAMMING LANGUAGE KNOWN AS APANENTLANG! THIS USES JAVASCRIPT, AND THIS PROGRAMMING LANGUAGE IS **STILL** IN DEVELOPMENT!

function lexer(code) {
  let a = code.length
  let target = ""
  let e = []
}
